export const metadata = {
  title: "CloseSea",
  description: "Generated by Next.js",
};
import "./styles/globals.css";
import { NavBar, Footer } from "../components/componentsindex";

const RootLayout = ({ children }) => {
  return (
    <html>
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
